# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0004_auto_20170710_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
