# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0005_auto_20170719_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
